# Generated by Django 3.2.9 on 2022-01-10 13:00

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', phone_field.models.PhoneField(max_length=12)),
                ('Password', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=100)),
                ('Create_Date', models.DateTimeField(max_length=100)),
                ('Last_Updated', models.DateTimeField()),
                ('Is_Active', models.BooleanField()),
            ],
        ),
    ]
